name: resolve

on:
  push:
    branches:
      - "release-*"

jobs:
  resolve:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Package
      run: swift package resolve