name: Combine Libraries

on:
  # Runs on workflow dispatch only
  workflow_dispatch:
    inputs:
      version:
        description: 'SDK Version Number'
        required: true
        type: string

# Sets permissions of the GITHUB_TOKEN to allow pushes
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "add-version"
  cancel-in-progress: true

env:
  VERSION: ${{ github.event.inputs.version }}

jobs:
  merge-libraries:
    name: Merge iOS and macOS Libraries
    runs-on: macos-13
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r .github/workflows/requirements.txt
      - name: Python Merge Script
        run: python .github/workflows/merge_libraries.py $VERSION
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Commit and Push Changes
        run: |
          git add Package.swift
          git commit -m "Automatically generated changes for version $VERSION"
          git push
      - name: Install GitHub CLI
        run: brew install gh
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $VERSION ./libs/*.zip -t $VERSION -n "Release notes for $VERSION" -p
 